Controllers films users
NikitaName/java-filmorate pull request #3
Opened 2022-12-26 19:39 UTC by NikitaName

2022-12-27 11:49 UTC, ErkinKasymaliev requested changes
Привет, неплохая работа, оставил комменты

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/validator/DateBefore.java
> +    String message() default "{Дата релиза не может быть раньше 1895-12-28}";
красота)

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/validator/FilmClassValidator.java
> +public class FilmClassValidator implements ConstraintValidator<DateBefore,LocalDate> {
давайте переименуем в DateBeforeValidator

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping("/films")
отлично что в одном месте указали path

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Getter
ох, а тут гетеры и сеттеры не нужны, уберите их

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        setMaxId(getMaxId() + 1);
давайте просто инкрементить

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                throw new ValidationException("Ошибка обновления фильма!");
тут не совсем верно кидать validationException, так как валидацию film прошел. У вас же ошибка что такого фильма у вас нет, лучше кинуть throw new ResponseStatusException(HttpStatus.NO_CONTENT, "фильма с таким id нет.");

2022-12-27 11:49 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@RestController
комменты такие как и в FilmController

2022-12-27 12:14 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/model/validator/FilmClassValidator.java
> +public class FilmClassValidator implements ConstraintValidator<DateBefore,LocalDate> {
Выполнено)

2022-12-27 12:18 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Getter
Убрал, сделал инкремент ++maxId

2022-12-27 12:18 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        setMaxId(getMaxId() + 1);
Скорректировал, ++maxId

2022-12-27 12:26 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                throw new ValidationException("Ошибка обновления фильма!");
Скорректировал, единственное оставил HttpStatus.INTERNAL_SERVER_ERROR, т.к. файл с тестами для Postman который прилагался хочет видеть возвращение этой ошибки.

2022-12-27 13:54 UTC, ErkinKasymaliev requested changes
оставил комменты

2022-12-27 13:54 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      @Getter
геттеры  и сеттеры вообще тут не нужны. Сеттеры и геттеры используется в моделях.

2022-12-27 13:54 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/validator/FilmClassValidator.java
> +public class FilmClassValidator implements ConstraintValidator<DateBeforeValidator,LocalDate> {
не не) FilmClassValidator надо было переименовать, а DateBefore оставить

2022-12-27 14:33 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      @Getter
Поторопился, убрал из контроллеров геттеры и сеттеры...

2022-12-27 14:34 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/model/validator/FilmClassValidator.java
> +public class FilmClassValidator implements ConstraintValidator<DateBeforeValidator,LocalDate> {
Вернул DateBefore, переименовал FilmClassValidator )

2022-12-28 07:42 UTC, ErkinKasymaliev approved these changes
Привет, теперь все круто, работа принята

2022-12-28 08:00 UTC, merged