Add database
NikitaName/java-filmorate pull request #6
Opened 2023-02-11 18:46 UTC by NikitaName

2023-02-12 09:57 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
также, не надо было удалять InMemoryUserStorage и InMemoryFilmStorage. смысл был в том, что научиться использовать @Qualifier и @Primary - ситуации где у вас несколько имплементаций сервиса. Восстановите эти классы.

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +@Qualifier("filmDbStorage")
лучше используйте @Qualifier при внедрении.
Название Бина лучше указывайте так @Service/@Component("filmDbStorage")

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +@Primary
норм

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +            log.debug("С id={} фильм не найден.", filmId);
отлично

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("filmDbStorage")
это тут не надо, у вас в FilmDbStorage уже @Primary стоит

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +        List<Film> films = jdbcTemplate.query(getFilmSql, (rs, rowNum) -> filmMapper(rs));
тут сперва вы запрашиваете все фильмы, а потом для каждого фильма запрашиваете его жанры и mpa в filmMapper. Так не пойдет, так как если у вас 1000 фильмов, то потом вы будете делать 2 тысячи запросов. И это совсем не круто. Вместо этого перепишите String getFilmSql = "select * from films;" с joinами, чтобы film сразу возвращались с рейтингами и жанрами.
Возможно данные будут дублироваться, так как на 1 фильм может приходится несколько жанров. тогда можно сделать следующее: String getFilmSql = "select * from films;" - это запрос переписываете с join таблицы mpa. Потом в FilmService в методе getFilms вызываете этот метода и получаете коллекцию фильмов, в которых заполнено поле mpa. Но вам надо заполнить поле Set<Genre>. Для этого в GenreDbStorage перепишите метод public List<Genre> getGengesFilm(long filmId) так что бы во входном параметре был List<Long> filmIds. То есть в одно запросе вы вытащите все filmId и их жанры. После заполняйте поле Set<Genre> в коллекции фильмов

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +    private boolean isRatingsMpa(int mpaId) {
перенесите это в слой сервиса и проводите проверки там

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +    private boolean isGenres(Set<Genre> genres) {
перенесите это в слой сервиса и проводите проверки там

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +        List<Film> films = jdbcTemplate.query(getFilmSql, (rs, rowNum) -> filmMapper(rs));
перепишите согласно этой логике методы getFilm и getPopularFilms

2023-02-12 09:57 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/dao/FriendsDao.java
> +public interface FriendsDao {
одни классы у вас Storage другие Dao. выберите один и его используйте

2023-02-12 21:39 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +@Qualifier("filmDbStorage")
Привет! Вернул InMemoryUserStorage и InMemoryFilmStorage. Пришлось переписать под расширенное задание 11 спринта...

2023-02-12 21:39 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("filmDbStorage")
Исправил

2023-02-12 21:42 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +        List<Film> films = jdbcTemplate.query(getFilmSql, (rs, rowNum) -> filmMapper(rs));
Переписал логику, но немного по-другому. Запрос к БД со множеством join всего один, но потом дубли убираю через промежуточный LinkedHashMap. В сервисе логику не менял.

2023-02-12 21:42 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +    private boolean isRatingsMpa(int mpaId) {
Перенёс проверки в сервис

2023-02-12 21:43 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/daoImpl/FilmDbStorage.java
> +    private boolean isGenres(Set<Genre> genres) {
Перенёс проверки в сервис

2023-02-12 21:43 UTC, NikitaName commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/dao/FriendsDao.java
> +public interface FriendsDao {
Скорректировал единообразно

2023-02-13 08:02 UTC, ErkinKasymaliev requested changes
привет, оставил 1 коммент

2023-02-13 14:29 UTC, ErkinKasymaliev approved these changes
работа принята

2023-02-13 17:59 UTC, merged